### ISSUE TITLE
Image not publicly available from GitHub Registry without auth

### ISSUE THREAD

**Issue by TomKriek** [lnsp/k8s-crash-informer#6]
[Currently it's not possible to pull the image without authenticating against the GitHub registry.](https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782) 

Is it possible to publish the image on https://hub.docker.com/ or some other public container registry?

**Comment by lnsp** [comment]
There actually is a Docker Hub-version available using `docker pull lnsp/crash-informer:latest`. I guess I should add that as the default image instead of GitHub Registry.

**Comment by lnsp** [comment]
I've updated the manifests, the problem should be resolved.

**Comment by TomKriek** [comment]
Alright super nice going to give this a shot on monday right away. Thanks for the clarification!
